/*
 * Donne Gowdru Biriyani Mane — site configuration
 * ------------------------------------------------------------------
 * Single source of truth for business details, imagery and integrations.
 * Edit this file to update the site; no layout changes are needed.
 *
 * DEMO STATE: address, phone, hours and payment details have not been
 * supplied yet. Placeholders are shown and the Call / Directions buttons
 * show a "to be confirmed" notice until real values are entered below.
 */
window.SITE = {
  /* Shows small "demo" annotations (sample prices, representative imagery,
     proposed copy). Set to false for the final client-facing launch. */
  demoMode: true,

  name: "Donne Gowdru Biriyani Mane",
  nameKannada: "ದೊನ್ನೆ ಗೌಡ್ರು ಬಿರಿಯಾನಿ ಮನೆ",
  /* Optional logo image (SVG/PNG). When null, the typographic wordmark is used. */
  logo: null,

  address: {
    display: "Address to be confirmed",
    city: "Bengaluru",
  },

  /* Fill these in to activate Call, WhatsApp booking and the phone links:
     phone: { display: "+91 98765 43210", tel: "+919876543210", whatsapp: "919876543210" } */
  phone: {
    display: "Phone to be confirmed",
    tel: null,
    whatsapp: null,
  },

  hours: {
    display: "Hours to be confirmed",
  },

  payments: "Payment options to be confirmed",

  links: {
    /* Google Maps directions link, e.g.
       "https://www.google.com/maps/dir/?api=1&destination=" + encodeURIComponent("<full address>") */
    directions: null,
    /* Google Maps embed URL, e.g.
       "https://www.google.com/maps?q=" + encodeURIComponent("<full address>") + "&z=16&output=embed" */
    mapEmbed: null,
    /* Link to the full menu (PDF or page). null shows a notice. */
    fullMenu: null,
    /* Online ordering link (own system or delivery partner). */
    order: null,
  },

  booking: {
    /* "whatsapp" — opens WhatsApp with a pre-filled enquiry (needs phone.whatsapp)
       "endpoint" — POSTs JSON to booking.endpoint (Formspree, webhook, etc.)
       "demo"     — validates only; nothing is sent                          */
    mode: "demo",
    endpoint: null,
    firstSlot: "12:00",
    lastSlot: "22:30",
    slotMinutes: 30,
    maxGuests: 30,
  },

  credit: {
    show: true,
    label: "Infinity Web & Apps",
    url: null,
  },

  /* Placeholder illustrations (generated by tools/illustrations.py) for the demo.
     Replace with real photographs: a local path ("assets/img/biryani.jpg"),
     a full URL, or an Unsplash photo ID ("photo-…"). */
  images: {
    hero: { src: "assets/illustrations/hero.svg", alt: "Illustration of a donne biryani spread with kabab, ghee roast and raita" },
    experience: { src: "assets/illustrations/about-handi.svg", alt: "Illustration of biryani in a copper handi" },
    experienceDetail: { src: "assets/illustrations/about-kabab.svg", alt: "Illustration of a plate of chicken kabab" },
    booking: { src: "assets/illustrations/booking-spread.svg", alt: "Illustration of a table set with biryani, kabab and curry" },
  },

  gallery: [
    { src: "assets/illustrations/g-handi.svg", alt: "Illustration of biryani in a copper handi", caption: "From the handi", shape: "tall" },
    { src: "assets/illustrations/g-kabab.svg", alt: "Illustration of chicken kabab with onion and lemon", caption: "Chicken kabab", shape: "square" },
    { src: "assets/illustrations/g-donne.svg", alt: "Illustration of chicken biryani in a leaf donne", caption: "Donne biryani", shape: "wide" },
    { src: "assets/illustrations/g-chicken.svg", alt: "Illustration of chicken ghee roast in a clay bowl", caption: "Chicken ghee roast", shape: "square" },
    { src: "assets/illustrations/g-nati.svg", alt: "Illustration of ragi mudde with nati koli saaru on a banana leaf", caption: "Mudde & saaru", shape: "square" },
    { src: "assets/illustrations/g-mutton.svg", alt: "Illustration of mutton pepper fry", caption: "Mutton pepper fry", shape: "square" },
    { src: "assets/illustrations/g-spread.svg", alt: "Illustration of a full non-veg spread", caption: "The full spread", shape: "wide" },
    { src: "assets/illustrations/g-drinks.svg", alt: "Illustration of majjige and gulab jamun", caption: "Majjige & jamun", shape: "wide" },
  ],
};
